# This is a basic workflow to help you get started with Actions

name: build

on:
  workflow_dispatch:

jobs:
  dive_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download dive
        run: |
          VERSION=$(curl https://github.com/wagoodman/dive/releases.atom| grep -oP '(?<=<title>v).*?(?=</title>)' | head -n1)
          wget https://github.com/wagoodman/dive/releases/download/v${VERSION}/dive_${VERSION}_linux_amd64.deb
          sudo dpkg -i dive_${VERSION}_linux_amd64.deb
      - name: find all directories
        run: |
          dive --ci ghcr.io/alexta69/metube:latest >> $GITHUB_STEP_SUMMARY
          
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: find all directories
        run: |
          find images/ -type d -mindepth 2 -maxdepth 4 
      - name: find all directories
        run: |
          find . -type f -mindepth 2 -maxdepth 4 -iname .docker -exec realpath "{}" \;
